# Generated by Django 5.2.4 on 2025-07-11 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("designs", "0002_alter_design_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_lead_time_days", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="designs.design",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        limit_choices_to={"role": "manufacturer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes_provided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Quotes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["design"], name="Quotes_design__7a8f4f_idx"),
                    models.Index(
                        fields=["manufacturer"], name="Quotes_manufac_f10b54_idx"
                    ),
                    models.Index(fields=["status"], name="Quotes_status_57b9bb_idx"),
                ],
            },
        ),
    ]
